default_profile = "postgresql"

[profiles.local-postgres]
theme = "gruvbox"
limit = 10_000
adapter = "postgres"
host = "host.docker.internal"
user = "postgres"
password = "Vr0GCDgzdleAc3ljwKct"
dbname = "dev"
port = 5432

[profiles.postgresql]
theme = "gruvbox"
limit = 10_000
adapter = "postgres"
host = "db-golang-v2.cjcc0ye241bn.ap-southeast-1.rds.amazonaws.com"
user = "postgres"
password = "054362770aA"
dbname = "dev"
port = 5432
