FROM golang:1.23-alpine AS builder

LABEL maintainer="By noobmaster"

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o worker cmd/worker/main.go

FROM alpine:latest

COPY --from=builder /build/worker /usr/local/bin/

EXPOSE 8000 

CMD ["/usr/local/bin/worker", "-config=env"]"]

